### ISSUE TITLE
undefined reference error when using azure-iot-sdk-c-dev=0.2.0.0-7xenial package to build

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-iot-sdk-c#543]
**SDK version used:** Apt-get Xenial: 0.2.0.0-7xenial

**Repro steps:** 
Build the c sample code using:
* https://github.com/VSChina/iot-edge-c-docker/blob/091b106e21c9b8d449a6ece9617b9bfea0b45896/modules/SampleModuleC/Dockerfile.amd64
* https://github.com/VSChina/iot-edge-c-docker/blob/091b106e21c9b8d449a6ece9617b9bfea0b45896/modules/SampleModuleC/iothub_client_sample_module_filter.byTemp.c
* https://github.com/VSChina/iot-edge-c-docker/blob/091b106e21c9b8d449a6ece9617b9bfea0b45896/modules/SampleModuleC/CMakeLists.txt

**Issue:**
Meet with bellow error:
```
Step 11/15 : RUN make
 ---> Running in 20119347fc8e
Scanning dependencies of target my_parson
[ 25%] Building C object CMakeFiles/my_parson.dir/parson.c.o
[ 50%] Linking C static library libmy_parson.a
[ 50%] Built target my_parson
Scanning dependencies of target iothub_client_sample_module_sender
[ 75%] Building C object CMakeFiles/iothub_client_sample_module_sender.dir/iothub_client_sample_module_filter.byTemp.c.o
[100%] Linking C executable iothub_client_sample_module_sender
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x35f): undefined reference to `iothub_device_auth_create'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x3a2): undefined reference to `iothub_device_auth_get_type'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x4d9): undefined reference to `iothub_device_auth_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x529): undefined reference to `iothub_device_auth_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Destroy':
(.text+0x55e): undefined reference to `iothub_device_auth_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Set_xio_Certificate':
(.text+0x6d7): undefined reference to `iothub_device_auth_generate_credentials'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Get_SasToken':
(.text+0xa7a): undefined reference to `iothub_device_auth_generate_credentials'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Get_TrustBundle':
(.text+0xe15): undefined reference to `iothub_device_auth_get_trust_bundle'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_core_ll.c.o): In function `IoTHubClientCore_LL_CreateFromEnvironment':
(.text+0x3bc8): undefined reference to `iothub_security_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libaziotsharedutil.a(uniqueid_linux.c.o): In function `UniqueId_Generate':
(.text+0xad): undefined reference to `uuid_generate'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libaziotsharedutil.a(uniqueid_linux.c.o): In function `UniqueId_Generate':
(.text+0xc7): undefined reference to `uuid_unparse'
collect2: error: ld returned 1 exit status
CMakeFiles/iothub_client_sample_module_sender.dir/build.make:95: recipe for target 'iothub_client_sample_module_sender' failed
make[2]: *** [iothub_client_sample_module_sender] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/iothub_client_sample_module_sender.dir/all' failed
make[1]: *** [CMakeFiles/iothub_client_sample_module_sender.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2
```

**Comment by jebrando** [comment]
We are working on a fix now.  We will let you know when we get it fixed.

**Comment by az-iot-builder-01** [comment]
@formulahendry, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Comment by dbmoderro** [comment]
Is the fix pushed into all Ubuntu PPA repos? I use ppa:aziotsdklinux/ppa-azureiot in Ubuntu 18.04 Bionic and do see the same linking issue. Adding those four extra libraries helps though.

**Comment by anuragcs027** [comment]
can you please write the steps how to add these 4 libraries to the build in ubuntu 16.04?
